spring.application.name=medicalSystem
  #spring.data.redis.database=9
  #spring.data.redis.host=127.0.0.1
  #spring.data.redis.port=6379
  #spring.data.redis.password=1234

spring.servlet.multipart.max-file-size=5MB
  ##  ?????
spring.servlet.multipart.max-request-size=10MB

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/medicalsystem?useUnicode=true&characterEncoding=utf-8&useSSL=false
spring.datasource.username=root
spring.datasource.password=1234
server.port=8121
  
  # MyBatis 配置
mybatis-plus.mapper-locations=classpath:/mapper/**/*.xml
mybatis-plus.global-config.db-config.id-type=auto
mybatis-plus.global-config.db-config.logic-delete-field=delete
mybatis-plus.global-config.db-config.logic-not-delete-value=0
mybatis-plus.global-config.db-config.logic-delete-value=1
mybatis-plus.type-aliases-package=cn.yam.domain
  # 打印sql语句
logging.level.cn.yam.mapper=debug

